export const tokens = {
  IParticipantRepository: Symbol('IParticipantRepository'),
  ITeamRepository: Symbol('ITeamRepository'),
  IPairRepository: Symbol('IPairRepository'),
  IParticipantQS: Symbol('IParticipantQS'),
  PrismaClient: Symbol('PrismaClient'),
  GetParticipantIndexUseCase: Symbol('GetParticipantIndexUseCase'),
  ValidateEmailUniquenessService: Symbol('ValidateEmailUniquenessService'),
  StoreParticipantUseCase: Symbol('StoreParticipantUseCase'),
  PatchParticipantUseCase: Symbol('PatchParticipantUseCase'),
  GetTeamIndexUseCase: Symbol('GetTeamIndexUseCase'),
  ITeamQS: Symbol('ITeamQS'),
  GetPairIndexUseCase: Symbol('GetPairIndexUseCase'),
  IPairQS: Symbol('IPairQS'),
  ChangePairUseCase: Symbol('ChangePairUseCase'),
  ChangePaiticipantUseCase: Symbol('ChangePaiticipantUseCase'),
  AssignTeamService: Symbol('AssignTeamService'),
  AssignPairService: Symbol('AssignPairService'),
  ChangeTaskProgressUseCase: Symbol('ChangeTaskProgressUseCase'),
  ITaskProgressRepository: Symbol('ITaskProgressRepository'),
  IParticipantSearchQS: Symbol('IParticipantSearchQS'),
  GetParticipantSearchUseCase: Symbol('GetParticipantSearchUseCase'),
}
