export const tokens = {
  IParticipantRepository: Symbol('IParticipantRepository'),
  ITeamRepository: Symbol('ITeamRepository'),
  IPairRepository: Symbol('IPairRepository'),
  IParticipantQS: Symbol('IParticipantQS'),
  PrismaClient: Symbol('PrismaClient'),
  GetParticipantIndexUseCase: Symbol('GetParticipantIndexUseCase'),
  ValidateEmailUniquenessService: Symbol('ValidateEmailUniquenessService'),
  StoreParticipantUseCase: Symbol('StoreParticipantUseCase'),
  PatchParticipantingUseCase: Symbol('PatchParticipantingUseCase'),
  PatchAdjourningUseCase: Symbol('PatchAdjourningUseCase'),
  PatchWithdrawnUseCase: Symbol('PatchWithdrawnUseCase'),
  GetTeamIndexUseCase: Symbol('GetTeamIndexUseCase'),
  ITeamQS: Symbol('ITeamQS'),
  GetPairIndexUseCase: Symbol('GetPairIndexUseCase'),
  IPairQS: Symbol('IPairQS'),
  ChangePairUseCase: Symbol('ChangePairUseCase'),
  ChangePaiticipantUseCase: Symbol('ChangePaiticipantUseCase'),
  AssignTeamService: Symbol('AssignTeamService'),
  AssignPairService: Symbol('AssignPairService'),
  ChangeTaskProgressUseCase: Symbol('ChangeTaskProgressUseCase'),
  ITaskRepository: Symbol('ITaskRepository'),
  ITaskProgressRepository: Symbol('ITaskProgressRepository'),
  IParticipantSearchQS: Symbol('IParticipantSearchQS'),
  GetParticipantSearchUseCase: Symbol('GetParticipantSearchUseCase'),
  AssignTaskProgressesService: Symbol('AssignTaskProgressesService'),
  EmailSender: Symbol('EmailSender'),
}
