export const tokens = {
  IParticipantRepository: Symbol('IParticipantRepository'),
  ITeamRepository: Symbol('ITeamRepository'),
  IPairRepository: Symbol('IPairRepository'),
  IParticipantQS: Symbol('IParticipantQS'),
  PrismaClient: Symbol('PrismaClient'),
  GetParticipantIndexUseCase: Symbol('GetParticipantIndexUseCase'),
  ValidateEmailUniquenessService: Symbol('ValidateEmailUniquenessService'),
  StoreParticipantUseCase: Symbol('StoreParticipantUseCase'),
  PutParticipantUseCase: Symbol('PutParticipantUseCase'),
  GetTeamIndexUseCase: Symbol('GetTeamIndexUseCase'),
  ITeamQS: Symbol('ITeamQS'),
  GetPairIndexUseCase: Symbol('GetPairIndexUseCase'),
  IPairQS: Symbol('IPairQS'),
  ChangePairUseCase: Symbol('ChangePairUseCase'),
}
